### PR TITLE
Updating Dependencies

### PR DESCRIPTION
**Pull request by cloewen8**
I have already updated my website that uses this boilerplate. Now I just want to give back for the great first step.

- [x] Lock dependencies to the latest minor version (instead of the latest). This helps to reduce the chance of an update to a dependency breaking the boilerplate (which has already occurred).
- [x] Switch to organization controlled dependencies.
- [x] Update gulp to 4.0.0.
- [x] Update babel to 4.0.0.
- [x] Replace gulp-clean (deprecated) with del.
- [x] Replace babel-preset-es2015 with @babel/preset-env and add a browserslist config (sample list).
- [x] Updated dev branch (#2).

### CODE REVIEW

**Comment by cloewen8** [comment]
I just want to know, if I contribute, would my changes make a difference:
- Would they be accepted?
- Are there plans to archive this instead?
- Is there an update I'm not aware of that is in the works?
- Or has this boilerplate just been abandoned?

@batzner

**Comment by batzner** [comment]
Hi @cloewen8, thanks for these improvements, this looks really good! Especially locking the dependency versions is more than overdue. Let me know when this PR is ready for review!

> I just want to know, if I contribute, would my changes make a difference:
> 
> * Would they be accepted?

Yes

> * Are there plans to archive this instead?

No

> * Is there an update I'm not aware of that is in the works?

No

> * Or has this boilerplate just been abandoned?

No. While I haven't worked on it after getting it to work for my blog, I am happy about any improvements.

**Comment by cloewen8** [comment]
It is ready, GitHub is preventing me from marking it as such. @batzner

**Comment by batzner** [comment]
Hi @cloewen8, I finally got to review and test your PR. Thank you very much for these changes!

**Pull request merged**
